module.exports = 
"El imperio azteca, también conocido"
+ "como mexica, fue una civilización "
+"prehispánica que habitó en el territorio "
+"mexicano entre el siglo XIV y XVI. "
+"Los aztecas eran un pueblo nómada y se "
+"cree que emigraron desde América del "
+"Norte hacia el valle, donde terminaron "
+"por asentarse en un islote cerca del "
+"lago de Texcoco. <audio src='soundbank://soundlibrary/human/amzn_sfx_people_walking_02'/>"
+"<audio src='soundbank://soundlibrary/backgrounds_ambience/construction_factory/construction_factory_03'/>"
+"Según la leyenda, "
+"esta civilización estaba en búsqueda"
+"constante de la tierra prometida, ya "
+"que el Dios Huitzilopochtli se les "
+"había presentado,dándoles el propósito de construir"
+"la ciudad que se convertiría <break strength='medium'/>"
+"en el imperio más grande de mesoamérica."
+"<break time = '0.3s'/> Para encontrar el lugar correcto, "
+"el pueblo azteca debía buscar a un águila devorando "
+"a una serpiente, posada sobre un nopal. "
+"<audio src='soundbank://soundlibrary/water/nature/nature_10'/>"
+"<break time = '1s'/>¿Te suena  <emphasis level='reduced'>conocida esta imagen? </emphasis>"
+"<prosody volume='x-loud'>¡Es el símbolo que tenemos en nuestra bandera nacional!"
+"</prosody>"
+"<break time = '1s'/>"
+"Poco a poco el pueblo azteca fue "
+"absorbiendo a otras civilizaciones "
+"y haciendo alianzas para beneficiarse "
+"de los recursos de sus aliados. Además, pronto se destacaría "
+"por el uso de la fuerza como método"
+"para imponer sus costumbres e idioma, "
+"<break time = '0.4s'/>"
+"el náhuatl. "
+"<audio src='soundbank://soundlibrary/battle/amzn_sfx_battle_yells_men_01'/>"
+"<break time = '1s'/>"
+"En esta cultura, el Tlatoani era el "
+"máximo exponente del gobierno, y su "
+"deber era tomar todas las decisiones "
+"concernientes al imperio; <break time = '0.4s'/>"
+"similar a la figura de un emperador. "
+"<break time = '0.7s'/>Tras la "
+"anexión de un territorio nuevo al "
+"imperio, este era dividido en "
+"provincias y se le asignaba un gobernador.";