module.exports = 
"El imperio azteca, también conocido"
+"como mexica, fue una civilización "
+"prehispánica que habitó en el territorio"
+"mexicano entre el siglo XIV y XVI. "
+"Los aztecas eran un pueblo nómada y se "
+"cree que emigraron desde América del "
+"Norte hacia el valle, donde terminaron"
+"por asentarse en un islote cerca del "
+"lago de Texcoco. <audio src="soundbank://soundlibrary/human/amzn_sfx_people_walking_02"/>"
+"<audio src="soundbank://soundlibrary/backgrounds_ambience/construction_factory/construction_factory_03"/>"
+"Según la leyenda, "
+"esta civilización estaba en búsqueda"
+"constante de la tierra prometida, ya "
+"que el Dios Huitzilopochtli se les "
+"había presentado,dándoles el propósito de construir"
+"la ciudad que se convertiría <break strength="medium"/>"
+"en el imperio más grande de mesoamérica."
+"<break time = '0.3s'/> Para encontrar el lugar correcto, "
+"el pueblo azteca debía buscar a un águila devorando "
+"a una serpiente, posada sobre un nopal. "
+"<audio src="soundbank://soundlibrary/water/nature/nature_10"/>"
+"<break time = '1s'/><break strength="medium"/>"
+"¿No te parece conocida esta imagen?"
+"<prosody volume="x-loud">¡Es el símbolo que tenemos en nuestra bandera nacional!"
+"</prosody>"

+"<break time = '1s'/>

+"Poco a poco el pueblo azteca fue "
+"absorbiendo a otras civilizaciones"
+"y haciendo alianzas para beneficiarse "
+"de los recursos de sus aliados. Además, pronto se destacaría"
+"por el uso de la fuerza como método"
+"para imponer sus costumbres e idioma, "
+"<break time = '0.4s'/>"
+"el náhuatl. "
+"<audio src="soundbank://soundlibrary/battle/amzn_sfx_battle_yells_men_01"/>"

+"<break time = '1s'/>

+"En esta cultura, el Tlatoani era el"
+"máximo exponente del gobierno, y su "
+"deber era tomar todas las decisiones"
+"concernientes al imperio; <break time = '0.4s'/>"
+"similar a la figura de un emperador. "
+"<break time = '0.7s'/>Tras la"
+"anexión de un territorio nuevo al"
+"imperio, este era dividido en "
+"provincias y se le asignaba un gobernador."

+"La civilización se encontraba"
+"disciplinadamente dividida en varios "
+"grupos sociales como <break time = '0.6s'/>"
+"la nobleza, <break time = '0.4s'/>"
+"Tlacatécatl, quienes eran los "
+"jefes de los grupos guerreros, "
+"<break time = '0.4s'/>"
+"Tlatoque, quienes eran los jefes de "
+"los diferentes estados <break time = '0.2s'/> y "
+"los sacerdotes. El resto de "
+"la población estaba conformada por "
+"artesanos, agricultores y esclavos."
+"<audio src="soundbank://soundlibrary/wood/moves/moves_02"/>"
+"<audio src="soundbank://soundlibrary/voices/crowds/crowds_10"/>"

<break time = '1s'/>

+"La economía de los aztecas se basaba"
+"en la pesca, la caza, el cultivo del"
+"maíz, el caco, el algodón, <break time = '0.2s'/>"
+"chiles y aguacate, <break time = '0.2s'/>"
+"entre <emphasis level="moderate">muchas</emphasis>"
+"otras plantas, <break time = '0.2s'/>"
+"así como el comercio y los tributos "
+"cobrados a pueblos sometidos. <break time = '0.2s'/>"
+"También fue muy valorada entre los aztecas "
+"la piedra obsidiana, con la cual se "
+"creaban armas y utensilios cortantes."
+"<break time = '0.3s'/>"
+"Su sistema de compra venta era el "
+"trueque en los mercados. "

<break time = '1s'/>

+"<audio src="soundbank://soundlibrary/voices/chorus/chorus_02"/>"
+"En cuanto a la religión, los aztecas "
+"eran politeístas. Es decir, adoraban "
+"a varios dioses. <break time = '0.3s'/>"
+"Además, era muy importante para "
+"ellos el realizar "
+"sacrificios, fuesen humanos o animales, "
+"ya que creían que la sangre era el "
+"alimento primordial de los dioses. "
+"Entre los dioses más importantes de "
+"esta cultura, se encuentran "
+"Huitzilopochtli, dios de la guerra;"
+"<break time = '0.5s'/>"
+"Tlaloc, dios de la lluvia; "
+"<break time = '0.5s'/>"
+"Quetzalcoatl, la serpiente emplumada "
+"<break time = '0.3s'/> y "
+"Coatlicue, la diosa madre. "
+"<audio src="soundbank://soundlibrary/voices/chorus/chorus_12"/>"

<break time = '1s'/>

+"En 1519, Hernán Cortés, desobedeciendo"
+"las órdenes expresas del gobernador de "
+"Cuba, llegó a la costa de México con "
+"aproximadamente 450 soldados. "
+"<break time = '0.5s'/>"
+"En el año 1520, lograron entrar a la capital del"
+"imperio y que el máximo gobernante de "
+"Tenochtitlán, Cuauhtémoc, se declarara"
+"vasallo del emperador Carlos V. "
+"<break time = '0.5s'/>"
+"De esta manera, todas las tierras pasaron"
+"a ser propiedad de la Corona de Castilla. "
+"<break time = '0.5s'/>"
+"El 29 de Junio de 1520, tras perder"
+"toda esperanza en él, los aztecas "
+"acabaron con la vida de su emperador."
+"<break time = '0.5s'/>"
+"Durante el resto de 1520 y gran "
+"parte de 1521, los castellanos fueron "
+"tomando el control de todos los "
+"pueblos y ciudades controlados por "
+"los mexicas, hasta bloquear las "
+"salidas de la ciudad lago. "
+"<break time = '1.1s'/>"
+"Es así como en el año 1521 encontramos "
+"el final de uno de los imperios más "
+"importantes de América. "
+"<break time = '0.5s'/>"
+"<audio src="soundbank://soundlibrary/explosions/fire/fire_03"/>"
