module.exports = {
  QUESTIONS_ES_MX: [
    {'¿Recuerdas como se llama nuestro dios de la lluvia?':['tlaloc ','tonatiuh','Huitzilopochtli','Cuahautemoc','Quetzalcoatl']},
    {'¿Cómo se llama nuestro juego favorito?':['Ullamaliztli.','cempazuchitl','chocolatl','apapachoa','huazolontle']},
    {'¿Cómo se llama la cancha  donde jugamos nuestro juego favorito?':['Tlachtli','Ullamaliztli.','cempazuchitl','chocolatl','cihuatl']},
    {'¿Cuál era el nombre con el que se le conoce a los esclavos chichimecas?' :['tlacotin','xocoatl','pipiltin ','tahtli','ixpolotl']},
    {'¿Cómo se llama la escuela donde estudian los hijos de la nobleza?':['Calmecac','Tlachtli','nenepilli','cueyatl','huitzitzilin']},
    {'¿Dónde estudian los hijos de casta baja?':['Cuicacalli','nenepilli','cueyatl','Calmecac','primaria']},
    {'¿Quiénes somos?':['Mexicas','tzopelic','Aztecas','Mayas']},
    {'¿Cuáles es nuestro idioma?':['N’ahuatl','Totonaca','Mexicatl','Zapotecatl','Maya']},
    {'¿Dónde enterramos a nuestros muertos?':['Debajo de sus casas','En la ceremonia de muertos','Cuando hay luna llena debajo del arbol mas frondoso','en la piramide del sol','En el rio a medio dia']},
    {'¿Cuál es el nombre de nuestra capital?':['Tenochtitlán','Ciudad de MExico','Mexica','Tepozcalli','No tenemos capital']},
    {'¿Cuándo fundamos nuestra capital?':['el año 2 Cali','el año 3 D.C','en 1521','en el año 0','el año 1 Cali']},
    {'¿Cuál es el nombre del grano que viene de la mazorca?':['etl','xocoatl','cacahuatl','ahuacatl','ahuehuetl']},
    {'¿Cómo se dice gracias en nahuatl?':['tlasojkamati','ahuehuetl','kema','amo','nimitstlatlaukilia']},
    {'¿Cómo se dice gracias en nahuatl?':['nimitstlatlaukilia','ahuehuetl','kema','amo','tlasojkamati']},
    {'¿Cuál es el animal chiquito que zumba en nuestros oidos y cuando te pica te da comezon?':['moyotl','michin','huilotl','cuauhtli','cuanacatl']},
    {'¿Qué significa Xomotl?':['ave viajera','por favor','sacrificio','lengua madre','madre']},
    {'¿Quién fue nuestro primer lider?':['Acamapichtli','cuanacatl','Xomotl','Tlaloc','michin']},
    {'¿Dónde descansan las almas de nuestros guerreros?':['La Casa del Sol','El Templo Mayor','Enterrados en el cementerio','Debajo de sus casas','Con sus familiares']},
    {'¿Cuántos cielos hay?':['13','1','No tienen','4','10']},
    {'¿Cuántos infiernos hay?':['9','2','10','400','13']},
    {'¿Qué es el cacao?':['Un regalo de los dioses','Un dulce','La eternidad','una ofrenda al sacerdote','el corazón de la ciudad']},
    {'¿Qué ave criamos?':['guajolot','pez','gallina','cerdo','aguila',]},
    {'¿Qué rango obtiene un guerrero cuando captura a su primer enemigo?':['Tlamani','Cabo','Cabotl','Xomotl','Acamapichtli',]},
    {'¿Cómo se llama el gorro que reciben nuestros guerreros despues de su segunda captura?': ['Tlahuizil','tequiha','cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl',],},
    {'¿Cómo se llaman los guerreros flecha?': ['Tequihua','Cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli',],},
    {'¿Cómo se le dice a los guerreros águila?': ['Cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua',],},
    {'¿Cómo se le dice a los guerreros jaguar?': ['Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua','Cuauhpilli',],},
    {'¿Cómo se le llama a un guerrero rapado?': ['Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua','Cuauhpilli','Ocelopipiltin',],},
    {'¿Cuál es nuestra arma favorita?': ['Maquahuitl','Teputzopilli','Quauhololli','Tematlatl','Átlatl','Tlahuitolli',],},
    {'¿Qué arma larga tenemos?': ['Teputzopilli','Quauhololli','Tematlatl','Átlatl','Tlahuitolli','Maquahuitl',],},
    {'¿Qué arma de larga distancia usamos?': ['Tlahuitolli','Teputzopilli','Quauhololli','Tematlatl','Átlatl','Maquahuitl',],},
    {'¿Cómo se llama el dios de la música y la danza?': ['Ozomatli','Xochiquetzal','Huitzilopochi','Tezcatlipoca','Xipe Totec','Chalchiuhtlique',],},
    {'¿Cómo se llama el dios de la muerte?': ['Mictlantechuhtli','Ozomatli','Xochiquetzal','Huitzilopochi','Tezcatlipoca','Xipe Totec',],}
  ],
  QUESTIONS_ES_ES: [
    {'Recuerdas como se llama nuestro dios de la lluvia?':['tlaloc ','tonatiuh','Huitzilopochtli','Cuahautemoc','Quetzalcoatl']},
    {'Cómo se llama nuestro juego favorito?':['Ullamaliztli.','cempazuchitl','chocolatl','apapachoa','huazolontle']},
    {'¿Cómo se llama la cancha  donde jugamos nuestro juego favorito?':['Tlachtli','Ullamaliztli.','cempazuchitl','chocolatl','cihuatl']},
    {'¿Cuál era el nombre con el que se le conoce a los esclavos chichimecas?' :['tlacotin','xocoatl','pipiltin ','tahtli','ixpolotl']},
    {'¿Cómo se llama la escuela donde estudian los hijos de la nobleza?':['Calmecac','Tlachtli','nenepilli','cueyatl','huitzitzilin']},
    {'¿Dónde estudian los hijos de casta baja?':['Cuicacalli','nenepilli','cueyatl','Calmecac','primaria']},
    {'¿Quiénes somos?':['Mexicas','tzopelic','Aztecas','Mayas']},
    {'¿Cuáles es nuestro idioma?':['N’ahuatl','Totonaca','Mexicatl','Zapotecatl','Maya']},
    {'¿Dónde enterramos a nuestros muertos?':['Debajo de sus casas','En la ceremonia de muertos','Cuando hay luna llena debajo del arbol mas frondoso','en la piramide del sol','En el rio a medio dia']},
    {'¿Cuál es el nombre de nuestra capital?':['Tenochtitlán','Ciudad de MExico','Mexica','Tepozcalli','No tenemos capital']},
    {'¿Cuándo fundamos nuestra capital?':['el año 2 Cali','el año 3 D.C','en 1521','en el año 0','el año 1 Cali']},
    {'¿Cuál es el nombre del grano que viene de la mazorca?':['etl','xocoatl','cacahuatl','ahuacatl','ahuehuetl']},
    {'¿Cómo se dice gracias en nahuatl?':['tlasojkamati','ahuehuetl','kema','amo','nimitstlatlaukilia']},
    {'¿Cómo se dice gracias en nahuatl?':['nimitstlatlaukilia','ahuehuetl','kema','amo','tlasojkamati']},
    {'¿Cuál es el animal chiquito que zumba en nuestros oidos y cuando te pica te da comezon?':['moyotl','michin','huilotl','cuauhtli','cuanacatl']},
    {'¿Qué significa Xomotl?':['ave viajera','por favor','sacrificio','lengua madre','madre']},
    {'¿Quién fue nuestro primer lider?':['Acamapichtli','cuanacatl','Xomotl','Tlaloc','michin']},
    {'¿Dónde descansan las almas de nuestros guerreros?':['La Casa del Sol','El Templo Mayor','Enterrados en el cementerio','Debajo de sus casas','Con sus familiares']},
    {'¿Cuántos cielos hay?':['13','1','No tienen','4','10']},
    {'¿Cuántos infiernos hay?':['9','2','10','400','13']},
    {'¿Qué es el cacao?':['Un regalo de los dioses','Un dulce','La eternidad','una ofrenda al sacerdote','el corazón de la ciudad']},
    {'¿Qué ave criamos?':['guajolot','pez','gallina','cerdo','aguila',]},
    {'¿Qué rango obtiene un guerrero cuando captura a su primer enemigo?':['Tlamani','Cabo','Cabotl','Xomotl','Acamapichtli',]},
    {'¿Cómo se llama el gorro que reciben nuestros guerreros despues de su segunda captura?': ['Tlahuizil','tequiha','cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl',],},
    {'¿Cómo se llaman los guerreros flecha?': ['Tequihua','Cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli',],},
    {'¿Cómo se le dice a los guerreros águila?': ['Cuauhpilli','Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua',],},
    {'¿Cómo se le dice a los guerreros jaguar?': ['Ocelopipiltin','Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua','Cuauhpilli',],},
    {'¿Cómo se le llama a un guerrero rapado?': ['Quachicqueh','tlacochcalcatl','tlahuizli','Tequihua','Cuauhpilli','Ocelopipiltin',],},
    {'¿Cuál es nuestra arma favorita?': ['Maquahuitl','Teputzopilli','Quauhololli','Tematlatl','Átlatl','Tlahuitolli',],},
    {'¿Qué arma larga tenemos?': ['Teputzopilli','Quauhololli','Tematlatl','Átlatl','Tlahuitolli','Maquahuitl',],},
    {'¿Qué arma de larga distancia usamos?': ['Tlahuitolli','Teputzopilli','Quauhololli','Tematlatl','Átlatl','Maquahuitl',],},
    {'¿Cómo se llama el dios de la música y la danza?': ['Ozomatli','Xochiquetzal','Huitzilopochi','Tezcatlipoca','Xipe Totec','Chalchiuhtlique',],},
    {'¿Cómo se llama el dios de la muerte?': ['Mictlantechuhtli','Ozomatli','Xochiquetzal','Huitzilopochi','Tezcatlipoca','Xipe Totec',],}
  ]};